name: Publish to Maven Central

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Git user
        run: |
          git config --global user.name "javagossip"
          git config --global user.email "javagossip@gmail.com"
      - name: Set up Java and credentials
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          server-id: central
          settings-path: ${{ github.workspace }}
          server-username: ${{ secrets.OSSRH_USERNAME }}
          server-password: ${{ secrets.OSSRH_PASSWORD }}
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg-passphrase: ${{ secrets.GPG_PASSPHRASE }}
      - name: Debug maven settings.xml
        run: cat $GITHUB_WORKSPACE/settings.xml
      - name: Publish to Maven Central
        run: ./mvnw release:prepare release:perform -B -s $GITHUB_WORKSPACE/settings.xml
        env:
            GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
